
- name: Configure apche vhost
  template: src=default.tpl dest=/etc/httpd/conf.d/000-default.conf

- name: set server name to localhost
  lineinfile: dest=/etc/httpd/conf/httpd.conf line="ServerName localhost"

- name: SELInux
  command: sestatus
  notify: 
    - restart httpd
  
- name: Ensure Apache running
  service: name=httpd state=started enabled=yes    